### ISSUE TITLE
Pop up scam/virus ads 

### ISSUE THREAD

**Issue by xsternal78** [rvaidun/befake#127]
I understand that you gotta monetize the page somehow to keep it alive or make some profit for your work, but I don't know man, this type of ads are the worse, wouldn't it be better if you just added normal ads that show at the screen at all times instead of using that shady popup mostly malware ads? 
![imagen](https://github.com/rvaidun/befake/assets/135463007/975a5297-0525-41b5-b2c6-022fd9839bc7)

**Comment by sigaloid** [comment]
![image](https://github.com/rvaidun/befake/assets/69441971/e65e586c-27d3-448c-ae2c-4a860fbf8a6a)

[Shameful behavior to see](https://github.com/search?q=repo%3Arvaidun%2Fbefake%20ads&type=code). That message has been removed from the about page: 
![image](https://github.com/rvaidun/befake/assets/69441971/67ea84f8-f014-469e-98e3-f89aeadfb6dc)
The actual HTML of the site also has an ad script injected: 
![image](https://github.com/rvaidun/befake/assets/69441971/851e65bb-4187-422a-b159-da08ca4a81b7)

For now, you can use https://befake.fly.dev/ - it has the ads removed.

@rvaidun, if this behavior is intentional by you to serve malicious, malware-ridden ads, you should be embarrassed.

**Comment by rvaidun** [comment]
Yeah I was testing it out, I tried getting approved for adsense but apparently site does not have enough unique content.
Currently using monetag but it's not that great. Didn't realize the ads were malicious, will remove now. Any suggestions on how to get this site approved with adsense?

**Comment by sigaloid** [comment]
You probably just have to wait it out. I would rather venmo you $20 or something so you don't have to put those kinds of ads up! How much is hosting?

**Comment by rvaidun** [comment]
![image](https://github.com/rvaidun/befake/assets/19789246/b8397b11-39d5-4c01-aaca-d81d82a67c8c)
This was cost for month of May

I've applied for adsense around 4 different times getting rejected each time. Trying to start a blog page with more information on reverse engineering and BeReal to see if that is enough unique content. Not sure what to do about that
