### ISSUE TITLE
View BeReals from past

### ISSUE THREAD

**Issue by Bastkapp** [rvaidun/befake#16]
I don't know if it is possible but
Can you add something to view BeReals from the past for example yesterday?
I've tried to take a look on my own but can't find out, where the posts get fetched and displayed

**Comment by rvaidun** [comment]
I've looked into this in the past. 
All the posts are fetched from the `https://mobile.bereal.com/api/feeds/friends` API. However, this API only returns the current days BeReals. Not sure if there is an API to get past BeReals from your friends.  There is an API to get your own past BeReals because of the memories API at `https://mobile.bereal.com/api/feeds/memories`.

Only way I can think of doing this is managing my own server which would save past BeReal's However the cost and storage will add up if I save every BeReal from every user on befake.fr. Also runs into the problem of how often to update my server since I don't know when the next BeReal will go off or when a user will post. Will have to have some type of listener to listen for the notifications and then save.

Simple solution is to just take a full page screenshot of the BeFake page.

**Comment by boehs** [comment]
Maybe use the filesystem API so storage is the user responsibility?
