### ISSUE TITLE
login not sending code

### ISSUE THREAD

**Issue by heightzyt** [rvaidun/befake#179]
Can you change the proxy so that it works on vercel please

**Comment by rvaidun** [comment]
don't know how since i haven't worked with vercel, but also not sure if it is possible. I tried making proxy work with firebase functions but I ran into issues with requests not being proxied properly and request was hanging indefinitely not receiving a response. Also, the proxy server needs to run on the backend and cannot be run client side and don't know if that is possible. For those of you trying to host I suggest hosting your own cors-anywhere server and pointing the API URL to the cors-anywhere server you are hosting.
