### ISSUE TITLE
Gif doesn't work

### ISSUE THREAD

**Issue by Saiitama** [rvaidun/befake#68]
I was testing the GIF feature, so i download a low size gif
![200w](https://user-images.githubusercontent.com/22159233/232344889-4f3c9f10-432a-4219-8c98-282f0542e065.gif)
On befake I see it as a gif (so it's moving) while on bereal is stationary
![IMG_20230416_235842](https://user-images.githubusercontent.com/22159233/232344953-137bf4dd-47b4-40d0-b78e-382d0b5772c0.jpg)
I also tested the "retake" feature and tried 999 to see if there is a limit, it says retake 0, so i probably exceeded the limit

**Comment by xKRISTOFx** [comment]
I've never seen moving image in bereal app and as far i know all bereal post photos are converted to .webp which doesn't support moving images. currently retake count doesn't work it is bug already fixed but it waits to be deployed. It was because hardcoded  zeros:
![image](https://user-images.githubusercontent.com/74738911/232351319-2e1e4c05-7459-4bf7-a1be-de2a8bab5396.png)
![image](https://user-images.githubusercontent.com/74738911/232351325-6b9c8f90-579d-46db-97ab-15bd7cf7addf.png)

**Comment by Saiitama** [comment]
> I've never seen moving image in bereal app and as far i know all bereal post photos are converted to .webp which doesn't support moving images. currently retake count doesn't work it is bug already fixed but it waits to be deployed. It was because hardcoded zeros: ![image](https://user-images.githubusercontent.com/74738911/232351319-2e1e4c05-7459-4bf7-a1be-de2a8bab5396.png) ![image](https://user-images.githubusercontent.com/74738911/232351325-6b9c8f90-579d-46db-97ab-15bd7cf7addf.png)

I tested the gif since it was in the feature

"You can also upload your own posts with photos from your camera roll, which will be visible to your friends. GIFs are also supported, meaning your BeReal can be a GIF!"

**Comment by rvaidun** [comment]
It's been patched by BeReal.

**Comment by rvaidun** [comment]
As of now the previews before tapping in are still moving

https://user-images.githubusercontent.com/19789246/232658050-9c99ce42-eee3-4e7f-b890-eb4d4877bea3.mov
